-- begin PSAOB_PS_SCHEDA
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCSTRSRI foreign key (SC_STRUTTURA_SRID) references PSAOB_SA_STRUTTURA(SRID)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCHE_SC_PAZIENTE foreign key (SC_PAZIENTE) references PSAOB_PAZIENTE(ID)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCCASMAN foreign key (SC_CASE_MANAGER) references SEC_USER(ID)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCPROPRI foreign key (SC_PROBLEMA_PRINC_ID) references PSAOB_PS_PROBLEMA_PRINCIPALE(ID)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCTIPESICOD foreign key (SC_TIPO_ESITO_CODICE) references PSAOB_PS_TIPO_ESITO_TAB(CODICE)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_PS_MEDICO_ACC foreign key (PS_MEDICO_ACC_ID) references SEC_USER(ID)^
alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_PS_MEDICO_DIM foreign key (PS_MEDICO_DIM_ID) references SEC_USER(ID)^
create index IDX_PSAOB_PSSCH_SCSTRSRI on PSAOB_PS_SCHEDA (SC_STRUTTURA_SRID)^
create index IDX_PSAOB_PSSCHE_SC_PAZIENTE on PSAOB_PS_SCHEDA (SC_PAZIENTE)^
create index IDX_PSAOB_PSSCH_SCCASMAN on PSAOB_PS_SCHEDA (SC_CASE_MANAGER)^
create index IDX_PSAOB_PSSCH_SCPROPRI on PSAOB_PS_SCHEDA (SC_PROBLEMA_PRINC_ID)^
create index IDX_PSAOB_PSSCH_SCTIPESICOD on PSAOB_PS_SCHEDA (SC_TIPO_ESITO_CODICE)^
create index IDX_PSAOB_PSSCH_PS_MEDICO_ACC on PSAOB_PS_SCHEDA (PS_MEDICO_ACC_ID)^
create index IDX_PSAOB_PSSCH_PS_MEDICO_DIM on PSAOB_PS_SCHEDA (PS_MEDICO_DIM_ID)^
-- end PSAOB_PS_SCHEDA
-- begin PSAOB_PAZIENTE
alter table PSAOB_PAZIENTE add constraint FK_PSAOB_PAZI_PZ_CITT_CTID foreign key (PZ_CITT_CTID) references PSAOB_SA_CITTADINANZA(CTID)^
alter table PSAOB_PAZIENTE add constraint FK_PSAOB_PAZ_PZ_COM_NAS_CMID foreign key (PZ_COM_NAS_CMID) references PSAOB_SA_COMUNE(CMID)^
alter table PSAOB_PAZIENTE add constraint FK_PSAOB_PAZ_PZ_COM_RES_CMID foreign key (PZ_COM_RES_CMID) references PSAOB_SA_COMUNE(CMID)^
create index IDX_PSAOB_PAZI_PZ_CITT_CTID on PSAOB_PAZIENTE (PZ_CITT_CTID)^
create index IDX_PSAOB_PAZ_PZ_COM_NAS_CMID on PSAOB_PAZIENTE (PZ_COM_NAS_CMID)^
create index IDX_PSAOB_PAZ_PZ_COM_RES_CMID on PSAOB_PAZIENTE (PZ_COM_RES_CMID)^
-- end PSAOB_PAZIENTE
-- begin PSAOB_PR_RICHIESTE
alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRICH_RIC_PAZIENTE foreign key (RIC_PAZIENTE_ID) references PSAOB_PAZIENTE(ID)^
alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRIC_RIC_MEDICO_RIC foreign key (RIC_MEDICO_RIC_ID) references SEC_USER(ID)^
alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRICH_PS_SCHEDA1 foreign key (PS_SCHEDA_ID) references PSAOB_PS_SCHEDA(ID)^
create index IDX_PSAOB_PRRICH_RIC_PAZIENTE on PSAOB_PR_RICHIESTE (RIC_PAZIENTE_ID)^
create index IDX_PSAOB_PRRIC_RICMEDRIC on PSAOB_PR_RICHIESTE (RIC_MEDICO_RIC_ID)^
create index IDX_PSAOB_PRRICH_PS_SCHEDA1 on PSAOB_PR_RICHIESTE (PS_SCHEDA_ID)^
-- end PSAOB_PR_RICHIESTE
-- begin PSAOB_PR_RICH_SA_PREST_LINK
alter table PSAOB_PR_RICH_SA_PREST_LINK add constraint FK_PPRSPL_PR_RICHIESTE foreign key (PR_RICHIESTE_ID) references PSAOB_PR_RICHIESTE(RICCODE)^
alter table PSAOB_PR_RICH_SA_PREST_LINK add constraint FK_PPRSPL_SA_PRESTAZIONI foreign key (SA_PRESTAZIONI_ID) references PSAOB_SA_PRESTAZIONI(PRID)^
-- end PSAOB_PR_RICH_SA_PREST_LINK
-- begin PSAOB_PS_SCHEDA_SA_DGN_LINK
alter table PSAOB_PS_SCHEDA_SA_DGN_LINK add constraint FK_PPSSDL_SA_DIAGNOSI foreign key (SA_DIAGNOSI_ID) references PSAOB_SA_DIAGNOSI(DGID)^
alter table PSAOB_PS_SCHEDA_SA_DGN_LINK add constraint FK_PPSSDL_PS_SCHEDA foreign key (PS_SCHEDA_ID) references PSAOB_PS_SCHEDA(ID)^
-- end PSAOB_PS_SCHEDA_SA_DGN_LINK
