alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCSTRSRI foreign key (SC_STRUTTURA_SRID) references PSAOB_SA_STRUTTURA(SRID)^
create index IDX_PSAOB_PSSCH_SCSTRSRI on PSAOB_PS_SCHEDA (SC_STRUTTURA_SRID)^
