alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCPROPRI foreign key (SC_PROBLEMA_PRINC_ID) references PSAOB_PS_PROBLEMA_PRINCIPALE(ID)^
create index IDX_PSAOB_PSSCH_SCPROPRI on PSAOB_PS_SCHEDA (SC_PROBLEMA_PRINC_ID)^
