alter table PSAOB_PR_RICH_SA_PREST_LINK add constraint FK_PPRSPL_PR_RICHIESTE foreign key (PR_RICHIESTE_ID) references PSAOB_PR_RICHIESTE(RICCODE)^
alter table PSAOB_PR_RICH_SA_PREST_LINK add constraint FK_PPRSPL_SA_PRESTAZIONI foreign key (SA_PRESTAZIONI_ID) references PSAOB_SA_PRESTAZIONI(PRID)^
