alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRIC_RIC_MEDICO_RIC foreign key (RIC_MEDICO_RIC_ID) references SEC_USER(ID)^
create index IDX_PSAOB_PRRIC_RICMEDRIC on PSAOB_PR_RICHIESTE (RIC_MEDICO_RIC_ID)^
