alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRIC_RIC_PS_SCHEDA foreign key (RIC_PS_SCHEDA_ID) references PSAOB_PS_SCHEDA(ID)^
alter table PSAOB_PR_RICHIESTE add constraint FK_PSAOB_PRRICH_RIC_PAZIENTE foreign key (RIC_PAZIENTE_ID) references PSAOB_PAZIENTE(ID)^
create index IDX_PSAOB_PRRIC_RIC_PS_SCHEDA on PSAOB_PR_RICHIESTE (RIC_PS_SCHEDA_ID)^
create index IDX_PSAOB_PRRICH_RIC_PAZIENTE on PSAOB_PR_RICHIESTE (RIC_PAZIENTE_ID)^
