alter table PSAOB_PS_SCHEDA add ( SC_TRG_IN integer ) ^
alter table PSAOB_PS_SCHEDA add ( SC_TRG_OUT integer ) ^
alter table PSAOB_PS_SCHEDA add ( SC_MOD_ACC varchar2(255) ) ^
alter table PSAOB_PS_SCHEDA add ( SC_ANAMNESI_INFERM varchar2(255) ) ^
alter table PSAOB_PS_SCHEDA add ( SC_CAUSA_DICHIARATA_ACC varchar2(255) ) ^
alter table PSAOB_PS_SCHEDA add ( SC_ANAMNESI_MEDICA1 clob ) ^
alter table PSAOB_PS_SCHEDA add ( SC_ANAMNESI_MEDICA2 clob ) ^
alter table PSAOB_PS_SCHEDA add ( SC_ANAMNESI_MEDICA3 clob ) ^
alter table PSAOB_PS_SCHEDA add ( SC_DIAGNOSI_USCITA_TXT clob ) ^
alter table PSAOB_PS_SCHEDA add ( SC_TIPO_ESITO varchar2(255) ) ^
alter table PSAOB_PS_SCHEDA add ( SC_SOLVENTE char(1) ) ^
alter table PSAOB_PS_SCHEDA add ( SC_NOTE_PRESCRIZIONI clob ) ^
