alter table PSAOB_PAZIENTE add constraint FK_PSAOB_PAZI_PZ_CITT_CTID foreign key (PZ_CITT_CTID) references PSAOB_SA_CITTADINANZA(CTID)^
create index IDX_PSAOB_PAZI_PZ_CITT_CTID on PSAOB_PAZIENTE (PZ_CITT_CTID)^
