alter table PSAOB_PS_SCHEDA add constraint FK_PSAOB_PSSCH_SCTIPESICOD foreign key (SC_TIPO_ESITO_CODICE) references PSAOB_PS_TIPO_ESITO_TAB(CODICE)^
create index IDX_PSAOB_PSSCH_SCTIPESICOD on PSAOB_PS_SCHEDA (SC_TIPO_ESITO_CODICE)^
